# -*- coding: utf-8 -*-
"""hindlerooth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HUGWT0GRPnuOpWec7u7oPI3SXdzxUCY
"""

file=open('hindle.txt','r')
string1=""
for i in file:
    i=i.replace("\n","")
    string1=string1+i

import nltk

nltk.download('averaged_perceptron_tagger')



import nltk
text =string1
lower_case = text.lower()
tokens = nltk.word_tokenize(lower_case)
tags = nltk.pos_tag(tokens)
nouns=[]
verbs=[]
preposition=[]
for i in range(0,len(tags)):
    if(tags[i][1]=='NN'):
        if tags[i][0] not in nouns:
            nouns.append(tags[i][0])
    elif(tags[i][1]=='VBN' or tags[i][1]=='VBP'):
        if tags[i][0] not in verbs:
            verbs.append(tags[i][0])
    elif(tags[i][1]=='IN'):
        if tags[i][0] not in preposition:
            preposition.append(tags[i][0])
print(nouns)
print(verbs)
print(preposition)
verb=input("enter verb")
noun=input("enter noun")
preposition=input("enter preposition")
dict1={}
lis=[]
lis.append(string1.count(noun))
lis.append(string1.count(noun+" "+preposition)
dict1[noun]=lis
lis2=[]
lis2.append(string1.count(verb))
lis2.append(string1.count(verb+" "+preposition)
dict1[verb]=lis2
print(dictio)

dict1={}
lis1=[1,2,3]
noun="hi"
dict1[noun]=lis1

print(dict1)

